"""Initial migration, adding phone number

Revision ID: 53c9c4891f88
Revises: 
Create Date: 2024-04-05 13:40:58.283499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c9c4891f88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('notifications', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weather_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('temp_threshold', sa.Float(), nullable=True),
    sa.Column('temp_condition', sa.String(length=50), nullable=True),
    sa.Column('wind_speed_threshold', sa.Float(), nullable=True),
    sa.Column('wind_speed_condition', sa.String(length=50), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_preference')
    op.drop_table('member')
    # ### end Alembic commands ###
